[package]
name = "bevy07_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# will use 0.8 even if the tutorial is for 0.7
[dependencies]
bevy = "0.8.0"
rand = "0.8.5"